services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Bind mount the current directory
      - ./files:/files
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
